dist:
  name: vespa-otelcol
  description: Basic OTel Collector distribution for Vespa
  output_path: ./vespa-otelcol
  otelcol_version: "0.94.0"
  version: "1.0.1"

exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.94.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter v0.94.0"
  - gomod: "go.opentelemetry.io/collector/exporter/loggingexporter v0.94.0"
  - gomod: "go.opentelemetry.io/collector/exporter/otlpexporter v0.94.0"

receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.94.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver v0.94.0"
  - gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.94.0"

processors:
  - gomod: "go.opentelemetry.io/collector/processor/batchprocessor v0.94.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.94.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.94.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.94.0"
